
```{r}
library(dplyr)
library(ggplot2)
library(sf)
library(spdep)
library(tidyverse)
library(ggforce)
```

```{r}
NWHL_data <- read.csv("https://raw.githubusercontent.com/bigdatacup/Big-Data-Cup-2021/main/hackathon_nwhl.csv")
head(NWHL_data)
```
```{r}
# Create rink plot function
plot_rink = function(p_object){
  
  require(ggforce)
  require(cowplot)
  require(tidyverse)
  
  upper_outline = data.frame(
    x = c(
      115,
      172 + 28*sin(seq(0,pi/2,length=20)),
      172 + 28*sin(seq(pi/2,0,length=20)),
      115
    ),
    y = c(
      0, 
      0 + 28 - 28*cos(seq(0,pi/2,length=20)),
      85 - 28 + 28*cos(seq(pi/2,0,length=20)),
      85
    )
  )
  
  lower_outline = data.frame(
    x = c(
      115,
      100-72 - 28*sin(seq(0,pi/2,length=20)),
      100-72 - 28*sin(seq(pi/2,0,length=20)),
      115
    ),
    y = c(
      0, 
      0 + 28 - 28*cos(seq(0,pi/2,length=20)),
      85 - 28 + 28*cos(seq(pi/2,0,length=20)),
      85
    )
  )
  
  p = p_object +
    ## FACEOFF CIRCLES ##
    geom_circle(data = data.frame(x0 = 100, y0 = 42.5, r = 15), aes(x0 = x0, y0 = y0, r = r), lwd = 0.5, col = "gray50", inherit.aes = FALSE) +
    geom_circle(data = data.frame(x0 = 169, y0 = 20.5, r = 15), aes(x0 = x0, y0 = y0, r = r), lwd = 0.5, col = "gray50", inherit.aes = FALSE) +
    geom_circle(data = data.frame(x0 = 169, y0 = 64.5, r = 15), aes(x0 = x0, y0 = y0, r = r), lwd = 0.5, col = "gray50", inherit.aes = FALSE) +
    geom_circle(data = data.frame(x0 = 31, y0 = 64.5, r = 15), aes(x0 = x0, y0 = y0, r = r), lwd = 0.5, col = "gray50", inherit.aes = FALSE) +
    geom_circle(data = data.frame(x0 = 31, y0 = 20.5, r = 15), aes(x0 = x0, y0 = y0, r = r), lwd = 0.5, col = "gray50", inherit.aes = FALSE) +
    ## FACEOFF DOTS ##
    geom_point(inherit.aes = FALSE, aes(y = 42.5, x = 100), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 20.5, x = 169), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 64.5, x = 169), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 20.5, x = 120), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 64.5, x = 120), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 20.5, x = 31), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 64.5, x = 31), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 20.5, x = 80), col = "gray50", size = 1) +
    geom_point(inherit.aes = FALSE, aes(y = 64.5, x = 80), col = "gray50", size = 1) +
    ## BLUE AND RED LINES ##
    annotate("segment", col = "gray50",  x = 75, xend = 75, y = 0, yend = 85, lwd = 0.5) +
    annotate("segment", col = "gray50", x = 100, xend = 100, y = 0, yend = 85, lwd = 0.5) +
    annotate("segment", col = "gray50",  x = 125, xend = 125, y = 0, yend = 85, lwd = 0.5) +
    ## NET AND GOAL LINE ##
    geom_segment(col = "gray50", inherit.aes = FALSE, lwd = 0.5, aes(y = 79.25, x = 11, yend = 5.75, xend = 11)) +
    geom_segment(col = "indianred", inherit.aes = FALSE, lwd = 0.5, aes(y = 39.5, x = 7.5, yend = 45.5, xend = 7.5)) + 
    geom_segment(col = "indianred", inherit.aes = FALSE, lwd = 0.5, aes(y = 39.5, x = 7.5, yend = 39.5, xend = 11)) +  
    geom_segment(col = "indianred", inherit.aes = FALSE, lwd = 0.5, aes(y = 45.5, x = 7.5, yend = 45.5, xend = 11)) +
    geom_segment(col = "gray50", inherit.aes = FALSE, lwd = 0.5, aes(y = 5.75, x = 189, yend = 79.25, xend = 189)) +
    geom_segment(col = "indianred", inherit.aes = FALSE, lwd = 0.5, aes(y = 39.5, x = 192.5, yend = 45.5, xend = 192.5)) + 
    geom_segment(col = "indianred", inherit.aes = FALSE, lwd = 0.5, aes(y = 39.5, x = 192.5, yend = 39.5, xend = 189)) +  
    geom_segment(col = "indianred", inherit.aes = FALSE, lwd = 0.5, aes(y = 45.5, x = 192.5, yend = 45.5, xend = 189)) +
    ## OUTLINE ##
    geom_path(data = upper_outline, aes(x = x, y = y), colour = "gray80", inherit.aes = FALSE, lwd = 0.5) +
    geom_path(data = lower_outline, aes(x = x, y = y), colour = "gray80", inherit.aes = FALSE, lwd = 0.5) +
    ## ADDITIONAL SPECS ##
    scale_x_continuous(expand = c(0, 0), limits = c(0,200)) + scale_y_continuous(expand = c(0,0), limits = c(0,85)) +
    coord_fixed() +
    theme_void()
  
  return(p)
}
```

```{r}
# Plot of Goals Scored
goal_data = NWHL_data %>% 
  filter(Event %in% c("Goal")) %>% 
  arrange(X.Coordinate)

plot_rink(ggplot(goal_data)) +
  geom_point(aes(x = X.Coordinate, y = Y.Coordinate, color = Detail.1))
```

```{r}
NWHL_data %>% 
  filter((Event == "Goal" & lag(Event) == "Zone Entry") | lead(Event == "Goal" & lag(Event) == "Zone Entry"))
  
NWHL_data %>% 
  filter((Event == "Goal" & lag(Event, n = 2) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 2) == "Zone Entry"), n = 2))

NWHL_data %>% 
  filter((Event == "Goal" & lag(Event, n = 3) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 3) == "Zone Entry"), n = 3))

NWHL_data %>% 
  filter((Event == "Goal" & lag(Event, n = 4) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 4) == "Zone Entry"), n = 4))

NWHL_data %>% 
  filter((Event == "Goal" & lag(Event, n = 5) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 5) == "Zone Entry"), n = 5))



# Combine all
zone_entry_plus_goals <- NWHL_data %>% 
  filter(
  ((Event == "Goal" & lag(Event) == "Zone Entry") | lead(Event == "Goal" & lag(Event) == "Zone Entry")) |
  ((Event == "Goal" & lag(Event, n = 2) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 2) == "Zone Entry"), n = 2)) |
  ((Event == "Goal" & lag(Event, n = 3) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 3) == "Zone Entry"), n = 3)) |
  ((Event == "Goal" & lag(Event, n = 4) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 4) == "Zone Entry"), n = 4)) |
  ((Event == "Goal" & lag(Event, n = 5) == "Zone Entry") | lead((Event == "Goal" & lag(Event, n = 5) == "Zone Entry"), n = 5))
  )

zone_entry <- 
  zone_entry_plus_goals %>% 
  filter(Event == "Zone Entry")

plot_rink(ggplot(zone_entry)) +
  geom_point(aes(x = X.Coordinate, y = Y.Coordinate, color = Detail.1))
```


```{r}
# Power Play / Penalty Kill
pp_goal_data = NWHL_data %>% 
  filter((Home.Team.Skaters < 5) | (Away.Team.Skaters < 5)) %>% 
  filter(Event %in% c("Goal"))

plot_rink(ggplot(pp_goal_data)) +
  geom_point(aes(x = X.Coordinate, y = Y.Coordinate, color = Detail.1))
```

```{r}
# Power Play / Penalty Kill Offesive Passes (Buffalo)
pp_pass_data = NWHL_data %>% 
  filter((Home.Team.Skaters < 5) | (Away.Team.Skaters < 5)) %>% 
  filter((Home.Team.Skaters > Away.Team.Skaters)) %>% 
  filter(Event %in% c("Play")) %>% 
  filter(Home.Team == "Buffalo Beauts")

plot_rink(ggplot(pp_pass_data)) +
  geom_segment(aes(x = X.Coordinate, xend = X.Coordinate.2, y = Y.Coordinate, yend = Y.Coordinate.2, color = Detail.1))
```